name: trott_gps
description: Application GPS Trottinette
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.3  # <- Ajout de la carte Google Maps

flutter:
  uses-material-design: true
