name: Build APK Definitif

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout depot
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          cache: true

      - name: Build APK Sans Soucis
        run: |
          flutter --disable-analytics

          # Si le dossier android n'existe pas, on le génère automatiquement
          if [ ! -d "android" ]; then
            echo "Génération de la structure Android du projet..."
            flutter create . --org com.example.trottgps --project-name trott_gps
          fi

          flutter pub get
          flutter build apk --debug

      - name: Stocker l'APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
